language: ruby
bundler_args: --without coverage
script: bundle exec rspec
gemfile:
  - gemfiles/Gemfile.travis
# before_install: some_command
# env:
#   - "rack=1.3.4"
rvm:
  - 2.0.0
  - 1.9.3
  # - 1.9.2 # code_metric 0.1.0 requires ruby 1.9.3 or greater
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
# matrix:
#   allow_failures:
#     - rvm: rbx-19mode
